version: '3.3'

services:
  evilginx2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 53:53/udp
    command: ["/bin/bash"]
    #command: ["/bin/evilginx", "-p", "/app/phishlets", "-debug", "-developer"]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app/:/root/.evilginx
      - ./app/phishlets:/app/phishlets
      - ./app/blacklists:/root/config/blacklist.txt
    stdin_open: true
    tty: true
